### ISSUE TITLE
Rebuild issue tracker

### ISSUE THREAD

**Issue by blahah** [PREreview/prereview-standup#11]
- [x] migrate issue labels
- [x] migrate relevant issues from other repos and from airtable
- [x] triage issues and assign milestones
